export const PUBLIC_URL = process.env.REACT_APP_PUBLIC_URL
export const INFURA_ID = process.env.REACT_APP_INFURA_ID
export const STORAGE_API_TOKEN = process.env.REACT_APP_STORAGE_API_TOKEN
export const LOCAL_STORAGE_PREFERENCES_CID_KEY =
  process.env.REACT_APP_LOCAL_STORAGE_PREFERENCES_CID_KEY
export const MORALIS_APP_ID = process.env.REACT_APP_MORALIS_APP_ID
export const MORALIS_SERVER_URL = process.env.REACT_APP_MORALIS_SERVER_URL
export const ETHPLORER_API_KEY = process.env.REACT_APP_ETHPLORER_API_KEY
